name: pangeo-streamflow
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - ipyleaflet
  - numba
  - pandas
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - dask
  - distributed
  - bokeh
  - nbserverproxy
  - jupyter
  - jupyterlab
  - tornado
  - lxml
  - zarr
  - intake
  - intake-xarray
  - graphviz
  - dask-kubernetes
  - cython
  - scikit-image
  - shapely
  - pip:
    - dask_labextension
    - soupsieve
    - gcsfs
    - "--editable=git+https://github.com/davidbrochart/mcmc.git#egg=mcmc"
