name: pangeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipywidgets
  - ipyleaflet
  - numba
  - pandas
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - dask
  - distributed
  - bokeh
  - nbserverproxy
  - jupyter
  - jupyterlab
  - tornado=5.1.1
  - lxml
  - zarr
  - intake
  - intake-xarray
  - graphviz
  - dask-kubernetes
  - cython
  - scikit-image
  - shapely
  - pip:
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
    - soupsieve
    - gcsfs
    - git+https://github.com/davidbrochart/mcmc.git#egg=mcmc
