channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - ipyleaflet
  - numba
  - pandas
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - pydap
  - dask
  - distributed
  - bokeh
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - lxml
  - zarr
  - intake
  - intake-xarray
  - graphviz
  - dask-kubernetes
  - cython
  - scikit-image
  - shapely
  - pip:
    - soupsieve
    - gcsfs
